CREATE TABLE `users` (
`users_id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`nama` VARCHAR(50) NOT NULL,
`email` VARCHAR(50) NOT NULL,
`password` VARCHAR(50) NOT NULL,
`role` VARCHAR(50) NOT NULL
) 

DROP TABLE user